# Site settings
title: 吕辉 （Hui Lv）
email: huilv@njnu.edu.cn
url: https://ktr-hubrt.github.io
description: "吕辉的个人空间！This Hui Lv's zone~"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: https://twitter.com/SBootstrap
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/ktr-hubrt/

# Build settings
markdown: kramdown
permalink: pretty
